export enum TransferenceRoutes {
  transference = "/transference",
  favoredIdentification = "/transference/favored-identification",
  favoredAccountSelection = "/transference/favored-account-selection",
  favoredName = "/transference/favored-name",
  value = "/transference/value",
  schedule = "/transference/schedule",
  description = "/transference/description",
  attachDocuments = "/transference/attachments",
  summary = "/transference/summary",
  completed = "/transference/transference-completed",
  voucherTransfer = "/transference/voucher",
  selectBank = "/transference/bank",
  selectAccountType = "/transference/account-type",
  bankBranch = "/transference/bank-branch",
  accountNumber = "/transference/account-number",
}
